// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/huangyul/go-webook/internal/pkg/authz"
	"github.com/huangyul/go-webook/internal/repository"
	"github.com/huangyul/go-webook/internal/repository/cache"
	"github.com/huangyul/go-webook/internal/repository/dao"
	"github.com/huangyul/go-webook/internal/service"
	"github.com/huangyul/go-webook/internal/service/sms"
	"github.com/huangyul/go-webook/internal/web"
	"github.com/huangyul/go-webook/ioc"
)

// Injectors from wire.go:

func InitService() *gin.Engine {
	cmdable := ioc.InitRedis()
	authzAuthz := authz.NewAuthz(cmdable)
	v := ioc.InitMiddlewares(cmdable, authzAuthz)
	db := ioc.InitDB()
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	smsService := sms.NewLocalService()
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	codeService := service.NewCodeService(smsService, codeRepository)
	userHandler := web.NewUserHandler(userService, codeService, authzAuthz)
	articleDAO := dao.NewArticleDAO(db)
	articleCache := cache.NewArticleCache(cmdable)
	articleRepository := repository.NewArticleRepository(articleDAO, articleCache)
	articleService := service.NewArticleService(articleRepository, userRepository)
	articleHandler := web.NewArticleHandler(articleService)
	engine := ioc.InitWebServer(v, userHandler, articleHandler)
	return engine
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis)

var userSet = wire.NewSet(dao.NewUserDAO, cache.NewRedisUserCache, repository.NewUserRepository, service.NewUserService, web.NewUserHandler)

var codeSet = wire.NewSet(cache.NewCodeCache, repository.NewCodeRepository, service.NewCodeService)

var smsSet = wire.NewSet(sms.NewLocalService)

var articleSet = wire.NewSet(dao.NewArticleDAO, cache.NewArticleCache, repository.NewArticleRepository, service.NewArticleService, web.NewArticleHandler)
