mysql:
  addr: "root:root@tcp(localhost:13316)/webook?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "127.0.0.1:16379"
  db: 0
  password: ""

kafka:
  addr: "localhost:9094"

grpc:
  addr: "127.0.0.1:8081"
